# Numpy
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
import numpy as np

In [3]:
# to count the occurrance of each value in a numpy array
arr= np.array([0,5,5,0,2,4,3,0,0,5,4,1,9,9])
np.bincount(arr)

array([4, 1, 1, 1, 2, 3, 0, 0, 0, 2], dtype=int64)

In [4]:
#How to remove from one array those item that exist in another
a= np.array([5,4,3,2,1])
b=np.array([4,8,9,10,1])
# From a remove all of b
np.setdiff1d(a,b)

array([2, 3, 5])

In [5]:
#how to sort a numpy array by a specific column in a 2D array
arr = np.array([[1,2,3],[4,5,6],[0,0,1]])
arr[arr[:,1].argsort()]

array([[0, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
# How to reverse a numpy array in the most efficient way
arr = np.array([9,10,1,2,0])
reverse_arr= arr[::-1]
reverse_arr

array([ 0,  2,  1, 10,  9])

In [8]:
# calculate percentile
arr = np.array([11,22,33,44,55,66,77])
perc= np.percentile(arr,40)  #return the 40th percentile
print(perc)

37.400000000000006


In [9]:
#To check for an empty (zero element) Array
arr = np.zeros((1,0))
arr

array([], shape=(1, 0), dtype=float64)

In [10]:
arr.size

0

In [11]:
# Find the indices of an array where a condition is true
arr = np.array([[9,8,7],[6,5,4],[3,2,1]])
arr>3

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [12]:
# To find maximum and minimum value of a given flattened array
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [13]:
max_value= np.amax(a)
min_value= np.amin(a)
print(max_value)
print(min_value)

3
0


In [15]:
# to calvulate the differance between the maximum and the minimum values of a given array along the 2nd axis
arr= np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
res= np.ptp(arr, 1)

In [17]:
res

array([3, 3, 3, 3])

In [18]:
res1= np.ptp(arr,0)

In [19]:
res1

array([12, 12, 12, 12])

In [20]:
med= np.median(arr)

In [21]:
med

7.5

In [22]:
mean=np.mean(arr)
std= np.std(arr)
var= np.var(arr)
print(mean)
print(std)
print(var)

7.5
4.6097722286464435
21.25


In [23]:
x=np.array([2,1,0])
y= np.array([2,3,3])
cov_arr=np.cov(x,y)

In [24]:
cov_arr

array([[ 1.        , -0.5       ],
       [-0.5       ,  0.33333333]])

In [25]:
# Person product-moment correlation coefficient
cross_cor=np.corrcoef(x,y)

In [26]:
cross_cor

array([[ 1.       , -0.8660254],
       [-0.8660254,  1.       ]])

In [27]:
# to compute the histogram of nums against the bins
nums= np.array([0.5,0.7,1.0,1.2,1.3,2.1])
bins= np.array([0,1,2,3])
np.histogram(nums,bins)

(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [28]:
#get the power of an array values element-wise
x=np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
np.power(x,3)

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

In [30]:
# to get true division of the element-wise array inputs
x= np.arange(10)
np.true_divide(x,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])